name: Update F1 Standings

on:
  schedule:
    # Runs every Sunday at 10 PM UTC (adjust if needed)
    - cron: '0 3 * * 1'
  workflow_dispatch: # allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate driver and constructor standings
        working-directory: Paddock
        run: |
          python driver_standings.py
          python constructor_standings.py

      - name: Commit and push updated JSON
        working-directory: Paddock
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          git commit -m "Auto-update standings [skip ci]" || echo "No changes to commit"
          git push
